### ISSUE TITLE
[asr.google.SpeechRecognizer]  Exception in thread "Thread-78" java.lang.IllegalStateException: Queue full

### ISSUE THREAD

**Issue by ivanbalashov239** [uzyovoys/aggregate#15]
сначала работает нормально, через какое то время/количество использований вот такая ошибка

```

Mar 03, 2016 2:31:05 PM com.aggregate.detector.key.KeyDetector
INFO: Keyset detected
Mar 03, 2016 2:31:05 PM Dispatcher
INFO: Listening...
Mar 03, 2016 2:31:05 PM Dispatcher
INFO: ASR state: start
Exception in thread "Thread-78" java.lang.IllegalStateException: Queue full
    at java.util.AbstractQueue.add(AbstractQueue.java:98)
    at java.util.concurrent.ArrayBlockingQueue.add(ArrayBlockingQueue.java:312)
    at com.aggregate.asr.google.SpeechRecognizer$RecorderThread.record(SpeechRecognizer.java:161)
    at com.aggregate.asr.google.SpeechRecognizer$RecorderThread.run(SpeechRecognizer.java:148)
Mar 03, 2016 2:31:05 PM Dispatcher
INFO: ASR state: rec
Mar 03, 2016 2:31:05 PM Dispatcher
INFO: ASR state: done

```

**Comment by ivanbalashov239** [comment]
вероятно #20  связана с этой ошибкой,  но не понятно, почему это происходит, куда теряется сигнал завершения "прослушки"/"релиз клавиш"

**Comment by morfeusys** [comment]
Нет, это не связанные вещи. Скорее всего проблема в коде модуля распознавания. Я уже назначил на себя задачу, спасибо.

**Comment by ivanbalashov239** [comment]
ключ спрятал

``` java
Mar 04, 2016 9:20:32 PM com.aggregate.detector.key.KeyDetector
INFO: Keys: [115, 65515, 65038, 63]
Mar 04, 2016 9:21:14 PM com.aggregate.asr.google.SpeechRecognizer
SEVERE: Cannot recognize
java.io.IOException: Server returned HTTP response code: 502 for URL: https://www.google.com/speech-api/v2/recognize?output=json&key=<KEY>&lang=ru-ru
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
    at com.aggregate.asr.google.SpeechRecognizer$RecognizerThread.run(SpeechRecognizer.java:244)


```

кнопки активации давно не нажимались, поймал ошибку.

**Comment by seniorivn** [comment]
fixed

**Comment by ivanbalashov239** [comment]
``` java
Mar 05, 2016 2:52:12 PM com.aggregate.detector.key.KeyDetector
INFO: Keyset detected
Mar 05, 2016 2:52:12 PM Dispatcher
INFO: Listening...
Mar 05, 2016 2:52:12 PM Dispatcher
INFO: ASR state: start
Mar 05, 2016 2:52:12 PM Dispatcher
INFO: ASR state: start
Mar 05, 2016 2:52:12 PM Dispatcher
INFO: ASR state: start
Exception in thread "Thread-113" java.lang.IllegalStateException: Queue full
    at java.util.AbstractQueue.add(AbstractQueue.java:98)
    at java.util.concurrent.ArrayBlockingQueue.add(ArrayBlockingQueue.java:312)
    at com.aggregate.asr.google.SpeechRecognizer$RecorderThread.record(SpeechRecognizer.java:161)
    at com.aggregate.asr.google.SpeechRecognizer$RecorderThread.run(SpeechRecognizer.java:148)
Mar 05, 2016 2:52:12 PM Dispatcher
INFO: ASR state: rec
Mar 05, 2016 2:52:12 PM Dispatcher
INFO: ASR state: rec
Mar 05, 2016 2:52:12 PM Dispatcher
INFO: ASR state: rec
Mar 05, 2016 2:52:26 PM Dispatcher
INFO: ASR state: done
Mar 05, 2016 2:52:26 PM Dispatcher
INFO: ASR state: end
Mar 05, 2016 2:52:26 PM Dispatcher
INFO: ASR state: done
Mar 05, 2016 2:52:26 PM Dispatcher
INFO: ASR state: done
Mar 05, 2016 2:52:26 PM Dispatcher
INFO: ASR state: end
Mar 05, 2016 2:52:50 PM com.aggregate.detector.key.KeyDetector
INFO: Keys: [3, 86, 65535]
Mar 05, 2016 2:52:50 PM com.aggregate.detector.key.KeyDetector
INFO: Keys: [1, 3, 86, 65535]
Mar 05, 2016 2:52:50 PM com.aggregate.detector.key.KeyDetector
INFO: Keyset detected
Mar 05, 2016 2:52:50 PM Dispatcher
INFO: Listening...
Mar 05, 2016 2:52:50 PM Dispatcher
INFO: ASR state: start
Mar 05, 2016 2:52:50 PM Dispatcher
INFO: ASR state: start
Mar 05, 2016 2:52:50 PM Dispatcher
INFO: ASR state: start
Exception in thread "Thread-119" java.lang.IllegalStateException: Queue full
    at java.util.AbstractQueue.add(AbstractQueue.java:98)
    at java.util.concurrent.ArrayBlockingQueue.add(ArrayBlockingQueue.java:312)
    at com.aggregate.asr.google.SpeechRecognizer$RecorderThread.record(SpeechRecognizer.java:161)
    at com.aggregate.asr.google.SpeechRecognizer$RecorderThread.run(SpeechRecognizer.java:148)
Mar 05, 2016 2:52:51 PM Dispatcher
INFO: ASR state: rec
Mar 05, 2016 2:52:51 PM Dispatcher
INFO: ASR state: rec
Mar 05, 2016 2:52:51 PM Dispatcher
INFO: ASR state: rec
Mar 05, 2016 2:52:55 PM Dispatcher
INFO: ASR state: done
Mar 05, 2016 2:52:55 PM Dispatcher
INFO: ASR state: done
Mar 05, 2016 2:52:55 PM Dispatcher
INFO: ASR state: done
Mar 05, 2016 2:52:55 PM Dispatcher
INFO: ASR state: end
Mar 05, 2016 2:52:55 PM Dispatcher
INFO: ASR state: end
Mar 05, 2016 2:52:56 PM Dispatcher
INFO: Processing...
Mar 05, 2016 2:52:56 PM Dispatcher
INFO: Processing...

```

при этом работает как то странно, судя по логу кажется несколько раз запускает распознавание, в модуле пока не разобрался, помочь не могу.

**Comment by morfeusys** [comment]
@seniorivn так я вроде фикс закомитил, вы его пробовали у себя?

**Comment by ivanbalashov239** [comment]
@Morfeusys упс, думал, что проверил, сейчас заного удалил модуль, скомпилял, добавил в агрегат, ошибки не появляются, но всё же ведёт себя странно, то есть он явно детектирует один запуск клавиатурой, но 2 раза начитает слушать, потом 2 раза обрабатывает запрос и 2 раза на него реагирует.

``` java

Mar 05, 2016 6:25:58 PM com.aggregate.detector.key.KeyDetector
INFO: Keyset detected
Mar 05, 2016 6:25:58 PM Dispatcher
INFO: Listening...
Mar 05, 2016 6:25:58 PM Dispatcher
INFO: ASR state: start
Mar 05, 2016 6:25:58 PM Dispatcher
INFO: ASR state: start
Mar 05, 2016 6:25:59 PM Dispatcher
INFO: ASR state: rec
Mar 05, 2016 6:25:59 PM Dispatcher
INFO: ASR state: rec
Mar 05, 2016 6:25:59 PM Dispatcher
INFO: ASR state: done
Mar 05, 2016 6:25:59 PM Dispatcher
INFO: ASR state: done
Mar 05, 2016 6:25:59 PM Dispatcher
INFO: ASR state: end
Mar 05, 2016 6:25:59 PM Dispatcher
INFO: ASR state: end
Mar 05, 2016 6:26:01 PM Dispatcher
INFO: Processing...
Mar 05, 2016 6:26:01 PM Dispatcher
INFO: Processing засыпай
Mar 05, 2016 6:26:01 PM Dispatcher
INFO: Processed in 1 ms: cmd.smplexecutor.sleep
Mar 05, 2016 6:26:01 PM com.aggregate.smplexecutor.Executor
WARNING: request is: засыпай
Mar 05, 2016 6:26:01 PM Dispatcher
INFO: Processing...
Mar 05, 2016 6:26:01 PM Dispatcher
INFO: Processing засыпай
Mar 05, 2016 6:26:01 PM Dispatcher
INFO: Processed in 0 ms: cmd.smplexecutor.sleep
Mar 05, 2016 6:26:01 PM com.aggregate.smplexecutor.Executor
WARNING: request is: засыпай
Mar 05, 2016 6:26:04 PM com.aggregate.detector.key.KeyDetector
INFO: Keys: [65515]
Mar 05, 2016 6:26:05 PM com.aggregate.detector.key.KeyDetector
INFO: Keys: [117, 65515]
Mar 05, 2016 6:26:05 PM com.aggregate.detector.key.KeyDetector
INFO: Keys: [104, 65515]
Mar 05, 2016 6:26:07 PM com.aggregate.detector.key.KeyDetector
INFO: Keys: [1]
Mar 05, 2016 6:26:07 PM com.aggregate.detector.key.KeyDetector
INFO: Keys: [64]
Mar 05, 2016 6:26:09 PM com.aggregate.detector.key.KeyDetector
INFO: Keys: [65293]
Mar 05, 2016 6:26:09 PM com.aggregate.detector.key.KeyDetector
INFO: Keys: [65027]
Mar 05, 2016 6:26:09 PM com.aggregate.detector.key.KeyDetector
INFO: Keys: [65027, 65038]
Mar 05, 2016 6:26:10 PM com.aggregate.detector.key.KeyDetector
INFO: Keys: [117, 65038]

```

**Comment by morfeusys** [comment]
@seniorivn агрегат перезапустите. Там сейчас ошибка с выгрузкой модулей есть.

**Comment by ivanbalashov239** [comment]
@Morfeusys  перезапустил, заработало, ясно, спасибо.
