### ISSUE TITLE
Ошибка в обработке строки URL в модуле dusi

### ISSUE THREAD

**Issue by popovanton0** [uzyovoys/aggregate#38]
Всё из-за пробела. Видимо надо процентную кодировку ссылки сделать. Лог:

INFO: Processing Что показывают по Первому каналу
мар 06, 2016 1:11:17 PM Dispatcher
INFO: Processed in 1 ms: cmd.dusi
мар 06, 2016 1:11:19 PM com.aggregate.dusi.DusiAssistant
INFO: Received: {"speech":"Открываю сайт m.tv.yandex.ru\/search?text=Первому каналу&type=channels","sas":false,"text":"Открываю сайт m.tv.yandex.ru\/search?text=Первому каналу&type=channels","agent":"LauncherAgent","response_uri":"http:\/\/m.tv.yandex.ru\/search?text=Первому каналу&type=channels"}
мар 06, 2016 1:11:19 PM com.aggregate.dusi.DusiAssistant
SEVERE: Cannot open URI
java.net.URISyntaxException: Illegal character in query at index 41: http://m.tv.yandex.ru/search?text=Первому каналу&type=channels
        at java.net.URI$Parser.fail(Unknown Source)
        at java.net.URI$Parser.checkChars(Unknown Source)
        at java.net.URI$Parser.parseHierarchical(Unknown Source)
        at java.net.URI$Parser.parse(Unknown Source)
        at java.net.URI.<init>(Unknown Source)
        at com.aggregate.dusi.DusiAssistant.processReply(DusiAssistant.java:88)
        at com.aggregate.dusi.DusiAssistant.access$100(DusiAssistant.java:24)
        at com.aggregate.dusi.DusiAssistant$WSClient.onMessage(DusiAssistant.java:111)
        at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:312)
        at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:368)
        at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:157)
        at org.java_websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:230)
        at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:188)
        at java.lang.Thread.run(Unknown Source)

**Comment by morfeusys** [comment]
Ошибка в модуле dusi - в обработке строки URL
