### ISSUE TITLE
Ошибка в новом модуле при инициализации в Aggregate

### ISSUE THREAD

**Issue by UUSR** [uzyovoys/aggregate#61]
@Morfeusys Получил ошибку при попытке установить свой модуль в Aggregate.
                    Не удалось декодировать: Непризнанные лексемы 'JDBC'

INFO: Deploying with conf C:\aggregate-0.0.1-bin.\conf\my-brain.json
мар 27, 2016 5:04:05 PM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
io.vertx.core.json.DecodeException: Failed to decode:Unrecognized token 'jdbc': was expecting ('true', 'false'
 or 'null')
 at [Source: {
  "url" : [jdbc:mysql://localhost:3306/MyBrain]
}; line: 2, column: 16]
        at io.vertx.core.json.Json.decodeValue(Unknown Source)
        at io.vertx.core.json.JsonObject.fromJson(Unknown Source)
        at io.vertx.core.json.JsonObject.<init>(Unknown Source)
        at io.vertx.core.buffer.impl.BufferImpl.toJsonObject(Unknown Source)
        at io.vertx.core.ay.a(Unknown Source)
        at io.vertx.core.impl.FutureImpl.checkCallHandler(Unknown Source)
        at io.vertx.core.impl.FutureImpl.setHandler(Unknown Source)
        at io.vertx.core.impl.ContextImpl.lambda$null$16(Unknown Source)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$18(Unknown Source)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(Unknown Source)
        at io.netty.channel.nio.NioEventLoop.run(Unknown Source)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by morfeusys** [comment]
Как я вижу, у вас в каком-то конфиге присутствует `"url" : [jdbc:mysql://localhost:3306/MyBrain]`
Это неправильный JSON. Почитайте что такое JSON на досуге.
Правильный - `"url" : "jdbc:mysql://localhost:3306/MyBrain"`

**Comment by UUSR** [comment]
@Morfeusys ,спасибо обязательно прочитаю.
