### ISSUE TITLE
Вопрос по динамическим шаблонам

### ISSUE THREAD

**Issue by popovanton0** [uzyovoys/aggregate#67]
Написал [слушателя](https://github.com/popovanton0/aggregate_ScreenShotMaker/blob/master/modules/programslauncher/src/main/java/com/popov/programslauncher/ProgramsLauncher.java#L40)  на событие: cmd.programslauncher.launchPatterns, в файле грамматики написал [это](https://github.com/popovanton0/aggregate_ScreenShotMaker/blob/master/modules/programslauncher/src/main/resources/programslauncher.xml#L20), и при установке модуля `INFO: Module maven:com.popov:programslauncher:1.0.0::programslauncher has been loaded with 0 commands`. Что я сделал не так ?

**Comment by morfeusys** [comment]
В вашей грамматике нет ни одной команды насколько видно. Вы описали только общий шаблон.
Более того, в названии шаблона рекомендую все же не использовать точки.

**Comment by popovanton0** [comment]
Исправил, теперь это:
SEVERE: Cannot load module maven:com.popov:programslauncher:1.0.0::programslauncher
io.vertx.core.I
        at io.vertx.core.H.a(Unknown Source)
        at io.vertx.core.H.a(Unknown Source)
        at io.vertx.core.H.a(Unknown Source)
        at io.vertx.core.k.a(Unknown Source)
        at java.util.ArrayList.forEach(Unknown Source)
        at io.vertx.core.k.a(Unknown Source)
        at java.util.ArrayList.forEach(Unknown Source)
        at io.vertx.core.k.a(Unknown Source)
        at io.vertx.core.a.a(Unknown Source)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$17(Unknown Source)
        at io.vertx.core.impl.OrderedExecutorFactory$OrderedExecutor.lambda$new$265(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by morfeusys** [comment]
@popovanton0 Без кода ничего сказать не могу к сожалению

**Comment by popovanton0** [comment]
[Вот он](https://github.com/popovanton0/aggregate/tree/master/modules/programslauncher)

**Comment by morfeusys** [comment]
@popovanton0 я там не вижу все так же ни одной команды в файле грамматики

**Comment by popovanton0** [comment]
забыл закоммитить, сейчас есть

**Comment by morfeusys** [comment]
Теперь вижу. Ошибка в том, что вы определили общий шаблон внутри команды. Так делать нельзя. Опишите ваш шаблон перед командой, а в шаблоне команды укажите ссылку на шаблон

``` xml
<pattern name="MyPattern" value="fuzzy://....."/>
<command>
  <pattern value="$MyPattern"/>
</command>
```

**Comment by popovanton0** [comment]
Работает, спасибо !
