### ISSUE TITLE
Модули на js. 

### ISSUE THREAD

**Issue by ghost** [uzyovoys/aggregate#73]
Кто нибудь писал уже модули на js? А то мой попытки не увенчались успехом. Не могу понять архитектуру модуля. Жду пустой проект модуля на js.

**Comment by morfeusys** [comment]
Архитектура модуля на JS расписана здесь https://github.com/uzyovoys/aggregate/wiki/Javascript 
А также в документации по Vertx. Что конкретно у вас не получается?

**Comment by ghost** [comment]
Как я понял, что бы создать модуль нужно 
1. сделать <имя модуля>.zip
2. В нем должен лежать файл <имя модуля>.json. В этом файле текст как в примере, только с начальным файлом для старта.
3. Это файл у меня просто для теста выглядит вот так:
`exports.vertxStart = function() {
 console.log("This is my verticle and it is starting...");
}` Но походу. 
4. Положить архив в deploy
Вот сам zip https://yadi.sk/d/ia67BiarrABZe 
Выходит ошибка когда стартует

**Comment by morfeusys** [comment]
Какая ошибка?

**Comment by ghost** [comment]
Active code page: 1251
Launching the Aggregate runtime...
Apr 22, 2016 7:20:04 AM Aggregate
INFO: Starting...
Apr 22, 2016 7:20:04 AM Aggregate
INFO: Initializing with C:\aggregate.\conf\aggregate.json
Apr 22, 2016 7:20:05 AM Aggregate
INFO: Starting sockJS server
Apr 22, 2016 7:20:05 AM Aggregate
INFO: SockJS server has been started on port 8888
Apr 22, 2016 7:20:05 AM ModuleRegistry
INFO: Auto deploy test.zip
Apr 22, 2016 7:20:05 AM ModuleRegistry
INFO: Deploying module maven:com.aggregate:key-detector:1.1.0::key-detector
Apr 22, 2016 7:20:05 AM ModuleRegistry
INFO: Deploying module maven:com.aggregate:browser:1.1.0::browser
Apr 22, 2016 7:20:05 AM ModuleRegistry
INFO: Deploying module maven:com.aggregate:date-time:1.0.1::date-time
Apr 22, 2016 7:20:05 AM ModuleRegistry
SEVERE: Cannot resolve module
io.vertx.core.aR: Descriptor is not found for module test
        at io.vertx.core.aW.a(Unknown Source)
        at io.vertx.core.aQ.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

Apr 22, 2016 7:20:05 AM Aggregate
INFO: Module registry is initialized

Вот

**Comment by morfeusys** [comment]
Пожалуйста пришлите ссылку на ваш репозиторий, где выложен весь код всего вашего проекта.
