### ISSUE TITLE
Не могу задеплоить ruby verticle

### ISSUE THREAD

**Issue by PaulAnnekov** [uzyovoys/aggregate#74]
Сформировал [архив](https://drive.google.com/open?id=0B8riTqvQMQTIZnhjWkhTSllyM0k) с модулем. Кладу в папку `deploy` и получаю в ответ:

```
Jun 05, 2016 11:36:17 PM ModuleRegistry
INFO: Deploying module sphinx
Jun 05, 2016 11:36:17 PM ModuleRegistry
INFO: Deployingsphinx with conf /home/steelrat/downloads/aggregate/conf/sphinx.json
Jun 05, 2016 11:36:17 PM ModuleRegistry
SEVERE: Cannot deploy sphinx
java.lang.ClassNotFoundException: repository/sphinx/app.rb
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at io.vertx.core.impl.JavaVerticleFactory.createVerticle(Unknown Source)
    at io.vertx.core.impl.DeploymentManager.createVerticles(Unknown Source)
    at io.vertx.core.impl.DeploymentManager.lambda$doDeployVerticle$157(Unknown Source)
    at io.vertx.core.impl.FutureImpl.checkCallHandler(Unknown Source)
    at io.vertx.core.impl.FutureImpl.setHandler(Unknown Source)
    at io.vertx.core.impl.DeploymentManager.doDeployVerticle(Unknown Source)
    at io.vertx.core.impl.DeploymentManager.doDeployVerticle(Unknown Source)
    at io.vertx.core.impl.DeploymentManager.deployVerticle(Unknown Source)
    at io.vertx.core.impl.VertxImpl.deployVerticle(Unknown Source)
    at io.vertx.core.aO.a(Unknown Source)
    at io.vertx.core.impl.FutureImpl.checkCallHandler(Unknown Source)
    at io.vertx.core.impl.FutureImpl.setHandler(Unknown Source)
    at io.vertx.core.impl.ContextImpl.lambda$null$16(Unknown Source)
    at io.vertx.core.impl.ContextImpl.lambda$wrapTask$18(Unknown Source)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(Unknown Source)
    at io.netty.channel.nio.NioEventLoop.run(Unknown Source)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by morfeusys** [comment]
Ok, посмотрю что там не так на вашем архиве

**Comment by morfeusys** [comment]
@PaulAnnekov проблема в вашем `app.rb` файле - вы в нем делаете `require('vertx')`, а нужно `require 'vertx/vertx'` как написано [в документации vertx](http://vertx.io/docs/vertx-core/ruby/#_in_the_beginning_there_was_vert_x)
